// Auth Action Types
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const AUTH_REFRESH_TOKEN_REQUEST = 'AUTH_REFRESH_TOKEN_REQUEST';
export const AUTH_REFRESH_TOKEN_SUCCESS = 'AUTH_REFRESH_TOKEN_SUCCESS';
export const AUTH_REFRESH_TOKEN_FAILURE = 'AUTH_REFRESH_TOKEN_FAILURE';

export const AUTH_UPDATE_USER_REQUEST = 'AUTH_UPDATE_USER_REQUEST';
export const AUTH_UPDATE_USER_SUCCESS = 'AUTH_UPDATE_USER_SUCCESS';
export const AUTH_UPDATE_USER_FAILURE = 'AUTH_UPDATE_USER_FAILURE';

export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';

export const AUTH_CHECK_TOKEN = 'AUTH_CHECK_TOKEN';
export const AUTH_INITIALIZE = 'AUTH_INITIALIZE';

export const AUTH_RESET_LOGIN_ATTEMPTS = 'AUTH_RESET_LOGIN_ATTEMPTS';
export const AUTH_INCREMENT_LOGIN_ATTEMPTS = 'AUTH_INCREMENT_LOGIN_ATTEMPTS';