// Constantes de tipo de acción para solicitudes generales
export const CLIENT_MAKE_REQ = "CLIENT_MAKE_REQ";
export const CLIENT_GETALL_SUCCESS = "CLIENT_GETALL_SUCCESS";
export const CLIENT_GETALL_COUNT_SUCCESS = "CLIENT_GETALL_COUNT_SUCCESS";
export const CLIENT_GETALL_FAIL = "CLIENT_GETALL_FAIL";
export const CLIENT_GET_SUCCESS = "CLIENT_GET_SUCCESS";
export const CLIENT_GET_FAIL = "CLIENT_GET_FAIL";
export const CLIENT_CREATE_SUCCESS = "CLIENT_CREATE_SUCCESS";
export const CLIENT_UPDATE_SUCCESS = "CLIENT_UPDATE_SUCCESS";
export const CLIENT_REMOVE_SUCCESS = "CLIENT_REMOVE_SUCCESS";


