export const GEO_MAKE_REQ = "GEO_MAKE_REQ";
export const GEO_GETTOWNS_SUCCESS = "GEO_GETTOWNS_SUCCESS";
export const GEO_GETLOCALITIES_SUCCESS = "GEO_GETLOCALITIES_SUCCESS";
export const GEO_GETPROVINCES_SUCCESS = "GEO_GETPROVINCES_SUCCESS";
export const GEO_GET_FAIL = "GEO_GET_FAIL";
