export const PROVIDER_MAKE_REQ = "PROVIDER_MAKE_REQ";
export const PROVIDER_CREATE_SUCCESS = "PROVIDER_CREATE_SUCCESS";
export const PROVIDER_CREATE_FAIL = "PROVIDER_CREATE_FAIL";
export const PROVIDER_UPDATE_SUCCESS = "PROVIDER_UPDATE_SUCCESS";
export const PROVIDER_GETS_SUCCESS = "PROVIDER_GETS_SUCCESS";
export const PROVIDER_GET_SUCCESS = "PROVIDER_GET_SUCCESS";
export const PROVIDER_GET_FAIL = "PROVIDER_GET_FAIL";
export const PROVIDER_GETS_FAIL = "PROVIDER_GETS_FAIL";
